### ISSUE TITLE
Any reference to "uin" as a unique identifier should be replaced with the defined uniqueIdeentifier from the config file

### ISSUE THREAD

**Issue by bagel-dawg** [bagel-dawg/accounts#6]
UIN is an pre-alpha variable from when the project was birthed in Bagel's incubator. It should be replaced with a uniqueIdentifier that is defined in the config file.

**Comment by bagel-dawg** [comment]
Can we drop a uniqueIdentifier concept in exchange for assuming email addresses will be globally unique between users? Or perhaps, the email address attribute will be the default uniqueIdentifier?

**Comment by diamonwiggins** [comment]
Closed in favor of #23
